#!/bin/bash
######################
#
#  Autor:   moer020
#  Version: 15072022
#
######################


# Variablen
LOG_OUT_DIR=./logs
SCRIPTNAME=ords_user.sql

echo "-- generated by '$(basename $0)'" > $SCRIPTNAME
create_temp_log_dir () {
        LOGDIR=$LOG_OUT_DIR/run_$(date +%Y%m%d%H%M)
        mkdir -p $LOGDIR
        echo "Logverzeichnis: $LOGDIR"
}
create () {
        create_temp_log_dir

        for user in "$@"; do
                user=$(echo "$user" | tr '[:upper:]' '[:lower:]')
                echo "create user $user identified by oracle PASSWORD EXPIRE PROFILE DEFAULT;" >> $SCRIPTNAME
                echo "grant create session to $user;" >> $SCRIPTNAME
                echo "BEGIN" >> $SCRIPTNAME
                echo "  ORDS.enable_schema(" >> $SCRIPTNAME
                echo "    p_enabled             => TRUE," >> $SCRIPTNAME
                echo "    p_schema              => '$user'," >> $SCRIPTNAME
                echo "    p_url_mapping_type    => 'BASE_PATH'," >> $SCRIPTNAME
                echo "    p_url_mapping_pattern => '$user'," >> $SCRIPTNAME
                echo "    p_auto_rest_auth      => TRUE" >> $SCRIPTNAME
                echo "  );" >> $SCRIPTNAME
                echo "  COMMIT;" >> $SCRIPTNAME
                echo "END;" >> $SCRIPTNAME
                echo "/" >> $SCRIPTNAME
        done
        USERLIST=$(IFS=,; printf '%s,' "$@")
        USERLIST=$(echo $USERLIST | sed 's/.$//')

        echo "s+ --silent --ifile $SCRIPTNAME --ofile $LOGDIR/$(basename ${SCRIPTNAME} .sql).out"
        echo "dbadmin --set_user_pwd --user=$(echo "$USERLIST" | tr '[:upper:]' '[:lower:]') --random"
        echo "nestpwd --get $(echo "$USERLIST" | tr '[:upper:]' '[:lower:]')"
}

USERLIST=$@

create $USERLIST
